### ISSUE TITLE
ImportError: No module named tensorflow

### ISSUE THREAD

**Issue by vignashrs** [datitran/raccoon-dataset#106]
Any one please help me out from the error which i couldn't overcome for a week???

after using the below command

python3 generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=images/

I received the following error

Traceback (most recent call last):
  File "generate_tfrecord.py", line 16, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow

To overcome this error????

**Comment by vignashrs** [comment]
also facing , this error?
flags = tf.app.flags
AttributeError: module 'tensorflow' has no attribute 'app'
anybody please help me out??

**Comment by jod98** [comment]
Replace "import tensorflow as tf" with "import tensorflow.compat.v1 as tf" if you are using Tensorflow 2.0 or greater :)

**Comment by vignashrs** [comment]
thanks @jod98 for your response and help
Now im getting below kind of error???

import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'

could u please help me to overcome?

**Comment by jod98** [comment]
I am having a similar same error. I am trying to convert my .csv file to a 'tfrecord' file. I was using tensorflow 2.0 but I heard that it wasn't supported for object_detection (what I am trying to do). I tried tensorflow 1.14 and 1.15 but still get an error. I am going to try used github repository branch for tensorflow 1.* and create my tfrecords file that way. I will let you know if I get it :)

**Comment by himanshisyadav** [comment]
Getting the following error with TF 1.12.0. I was using 1.14.0 before and had issues. 

`/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "autoencoder_test_MLP_basic.py", line 24, in <module>
    from deephyp import autoencoder
  File "../deephyp/autoencoder.py", line 16, in <module>
    import tensorflow.compat.v1 as tf
ImportError: No module named 'tensorflow.compat.v1'
`
