### ISSUE TITLE
ERROR in generate_tfrecord.py ( AttributeError: output_path )

### ISSUE THREAD

**Issue by Aashiq24** [datitran/raccoon-dataset#111]
hello everyone, i have been struggling to solve this issue for quite some time now. whenever i run generate_tf.py script, i encounter the following error message:

**Traceback (most recent call last):
  File "C:/Users/MSI-GF63/Desktop/raccoon_dataset-master/generate_tfrecord.py", line 101, in <module>
    tf.app.run()
  File "C:\Users\MSI-GF63\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\MSI-GF63\anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\MSI-GF63\anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:/Users/MSI-GF63/Desktop/raccoon_dataset-master/generate_tfrecord.py", line 86, in main
    print(FLAGS.output_path)
  File "C:\Users\MSI-GF63\anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "C:\Users\MSI-GF63\anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 473, in __getattr__
    raise AttributeError(name)
AttributeError: output_path**

can someone please help me with this? i am using windows and running the script on Pycharm

**Comment by hostankit** [comment]
change the tf.app to tf.compat.v1.app
