### ISSUE TITLE
Error in tf.python_io.TFRecordWriter

### ISSUE THREAD

**Issue by rahulramesh3321** [datitran/raccoon-dataset#84]
Hi All,

While running the code  **writer = tf.python_io.TFRecordWriter(FLAGS.output_path)** 
below are the errors occured : 

> 

writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
Traceback (most recent call last):

  File "<ipython-input-84-ee305eb7983f>", line 1, in <module>
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)

  File "D:\anaconda\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 210, in __init__
    compat.as_bytes(path), options._as_record_writer_options(), status)

  File "D:\anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))

NotFoundError: Failed to create a NewWriteableFile:  : The system cannot find the path specified.
; No such process
> 
I believe this is respective to the location of my files.
Below are the details of location of my files:
 'C:/Users/1010141/Desktop/Object-Detection/Data/Train.csv' *CSV file is 
 'C:/Users/1010141/Desktop/Object-Detection/Image/Train *Images and excel file is kept
C:\Users\1010141\Desktop\Object-Detection\ * My scripts is kept
C:\Users\1010141\Desktop\model\models-master\research * Object_detection directory is kept
D:\anaconda\pkgs\tensorflow-gpu-1.10.0-py36_0\Lib\site-packages\tensorflow * Tensorflow is kept.

Please help me .

**Comment by pc2005** [comment]
Please check my solution in issue #41 and see if it helps.

**Comment by patelalay231** [comment]
python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=images/
