### ISSUE TITLE
How to use tf.python_io.TFRecordWriter in Tensorflow 2.0 (generate_tfrecord.py)

### ISSUE THREAD

**Issue by ElHo1** [datitran/raccoon-dataset#90]
I get this error:
File "generate_tfrecord.py", line 102, in <module>
main()
File "generate_tfrecord.py", line 89, in main
writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
AttributeError: module 'tensorflow' has no attribute 'python_io'

What do i have to use instead?

**Comment by MAkC8** [comment]
use this :
```python
tf.compat.v1.python_io

```

**Comment by aledalgrande** [comment]
Or now that TF2 is out:
```
tf.io.TFRecordWriter
```

https://www.tensorflow.org/api_docs/python/tf/io/TFRecordWriter

**Comment by BookPlus2020** [comment]
use   tf.compat.v1.python_io.TFRecordWriter   instead of   tf.python_io.TFRecordWriter    
        tf.compat.v1.app.run()     instead of     tf.app.run()
        flags = tf.compat.v1.app.flags       instead of    flags = tf.app.flags

**Comment by BookPlus2020** [comment]
use      tf.compat.v1.python_io.TFRecordWriter        instead of          tf.python_io.TFRecordWriter
           tf.compat.v1.app.run()                                   instead of           tf.app.run()
           tf.compat.v1.app.flags                                    instead of          tf.app.flags

**Comment by chuasonglin** [comment]
> use tf.compat.v1.python_io.TFRecordWriter instead of tf.python_io.TFRecordWriter
> tf.compat.v1.app.run() instead of tf.app.run()
> tf.compat.v1.app.flags instead of tf.app.flags

I did all of this and I still have this problem. Help.

(tensorflow) C:\Users\chua_\ProjectsForFun\Project3_OwnObjectDetector>python generate_tfrecord.py -- csv_input=images/train_labels.csv --image_dir=images/train --output_path=train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 110, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\chua_\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\chua_\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\chua_\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 96, in main
    writer = tf.compat.v1.python_io.TFRecordWriter(FLAGS.output_path)
  File "C:\Users\chua_\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\lib\io\tf_record.py", line 218, in __init__
    compat.as_bytes(path), options._as_record_writer_options(), status)
  File "C:\Users\chua_\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\errors_impl.py", line 556, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile:  : The system cannot find the path specified.
; No such process

**Comment by chuasonglin** [comment]
We need to make sure the py script follows the format for tf2: 
Brushing up @BookPlus2020 answer:

Open the generate_tfrecord.py file and make these changes: 
1. use tf.compat.v1.python_io.TFRecordWriter instead of tf.python_io.TFRecordWriter
2. tf.compat.v1.app.run() instead of tf.app.run()
3. tf.compat.v1.app.flags instead of tf.app.flags
4. tf.gfile.GFile to tf.io.gfile.GFile

**Comment by jp3spinelli** [comment]
@chuasonglin I followed your revisions and keep getting this error:
$ python3 generate_tfrecord.py --csv_input=data/Train_labels.csv --output_path=data/train.record --image_dir=Camera pictures/Train/
Traceback (most recent call last):
  File "generate_tfrecord.py", line 99, in <module>
    tf.compat.v1.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 90, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 45, in create_tf_example
    encoded_jpg = fid.read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
    self._preread_check()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: Camera/Camera-mount-and-Raspberry-Pi.png; No such file or directory

**Comment by amagzari** [comment]
> tf.compat.v1.app.run()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/absl/app.py", line 299, in run
> _run_main(main, args)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
> sys.exit(main(argv))
> File "generate_tfrecord.py", line 90, in main
> tf_example = create_tf_example(group, path)
> File "generate_tfrecord.py", line 45, in create_tf_example
> encoded_jpg = fid.read()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
> self._preread_check()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
> self._read_buf = _pywrap_file_io.BufferedInputStream(
> tensorflow.python.framework.errors_impl.NotFoundError: Camera/Camera-mount-and-Raspberry-Pi.png; No such file or directory



> @chuasonglin I followed your revisions and keep getting this error:
> $ python3 generate_tfrecord.py --csv_input=data/Train_labels.csv --output_path=data/train.record --image_dir=Camera pictures/Train/
> Traceback (most recent call last):
> File "generate_tfrecord.py", line 99, in
> tf.compat.v1.app.run()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/absl/app.py", line 299, in run
> _run_main(main, args)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
> sys.exit(main(argv))
> File "generate_tfrecord.py", line 90, in main
> tf_example = create_tf_example(group, path)
> File "generate_tfrecord.py", line 45, in create_tf_example
> encoded_jpg = fid.read()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
> self._preread_check()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
> self._read_buf = _pywrap_file_io.BufferedInputStream(
> tensorflow.python.framework.errors_impl.NotFoundError: Camera/Camera-mount-and-Raspberry-Pi.png; No such file or directory

fixed the set of errors?
