### ISSUE TITLE
 NewRandomAccessFile failed to Create/Open: C:\Tensorflow\workspace        raining_demonnotations/label_map.pbtxt : The filename, directory name, or volume label syntax is incorrect. ; Unknown error

### ISSUE THREAD

**Issue by bebop-boop** [datitran/raccoon-dataset#92]
I am using windows 10, python 3.7. While I was trying to run train.py fpr custom object detection i was facing below issue: 
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Asus\Miniconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\Asus\Miniconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\Users\Asus\Miniconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\legacy\trainer.py", line 280, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\Users\Asus\Miniconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\legacy\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\Users\Asus\Miniconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 124, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "C:\Users\Asus\Miniconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\data_decoders\tf_example_decoder.py", line 307, in __init__
    default_value=''),
  File "C:\Users\Asus\Miniconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\data_decoders\tf_example_decoder.py", line 59, in __init__
    label_map_proto_file, use_display_name=False)
  File "C:\Users\Asus\Miniconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\utils\label_map_util.py", line 164, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "C:\Users\Asus\Miniconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\utils\label_map_util.py", line 133, in load_labelmap
    label_map_string = fid.read()
  File "C:\Users\Asus\Miniconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Users\Asus\Miniconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\Asus\Miniconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: NewRandomAccessFile failed to Create/Open: C:\Tensorflow\workspace        raining_demonnotations/label_map.pbtxt : The filename, directory name, or volume label syntax is incorrect.
; Unknown error

**Comment by minump** [comment]
Any update? I am facing the same issue.

**Comment by SJosh99** [comment]
Were you able to find a solution to this? If so, pls let me know @bebop-boop
