### ISSUE TITLE
error using generate_tfrecord

### ISSUE THREAD

**Issue by vgilabert94** [datitran/raccoon-dataset#96]
Hi people, Im working in a Object Detection project and when i execute the generate_tfrecord.py, I have this error:

(tensorflow1) c:\tensorflow1\research\object_detection\images>python generate_tfrecord.py --csv_input=test_labels.csv --output_path=test.record --image_dir=test/

WARNING: Logging before flag parsing goes to stderr.
W0722 17:10:14.657933  9896 deprecation_wrapper.py:119] From generate_tfrecord.py:106: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0722 17:10:14.661933  9896 deprecation_wrapper.py:119] From generate_tfrecord.py:92: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

Traceback (most recent call last):
  File "generate_tfrecord.py", line 106, in <module>
    tf.app.run()
  File "C:\Anaconda\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Anaconda\envs\tensorflow1\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Anaconda\envs\tensorflow1\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 95, in main
    grouped = split(examples, 'filename')
  File "generate_tfrecord.py", line 46, in split
    gb = df.groupby(group)
  File "C:\Anaconda\envs\tensorflow1\lib\site-packages\pandas\core\generic.py", line 7896, in groupby
    **kwargs
  File "C:\Anaconda\envs\tensorflow1\lib\site-packages\pandas\core\groupby\groupby.py", line 2478, in groupby
    return klass(obj, by, **kwds)
  File "C:\Anaconda\envs\tensorflow1\lib\site-packages\pandas\core\groupby\groupby.py", line 391, in __init__
    mutated=self.mutated,
  File "C:\Anaconda\envs\tensorflow1\lib\site-packages\pandas\core\groupby\grouper.py", line 621, in _get_grouper
    raise KeyError(gpr)
KeyError: 'filename'

Somebody can help me or he have been the same error?
I need your help.

**Comment by ilyes-hamrouni** [comment]
you should check the tensorflow version. it should be 1.2.1

**Comment by Zeakles** [comment]
I have the same Error
